version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - APP_URL=${APP_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app
      - /app/node_modules